import sqlite3
conn = sqlite3.connect("Hospital.db")
getID = input("Enter the Patient id- ")
getName = input("Enter the Name- ")
getAdd = input("Enter Address- ")
getPhno = input("Enter Phone Number- ")
getEmail = input("Enter the Email- ")
getPincode = input("Enter the Pincode- ")
cursor = conn.execute("UPDATE PATIENTS SET NAME='"+getName+"',ADDRESS='"+getAdd+"',PHNO='"+getPhno+"',EMAIL_ID='"+getEmail+"',PINCODE='"+getPincode+"' WHERE ID="+getID)
conn.commit()
print("Entry Updated successfully")
cursor = conn.execute("SELECT * FROM PATIENTS WHERE ID="+getID)
print("UPDATED RECORD")
for i in cursor:
    print("id-", i[0])
    print("Name-", i[1])
    print("Address-", i[2])
    print("Phone Number-", i[3])
    print("Email-", i[4])
    print("Pincode-", i[5])
    print("------------------------------------------------------")
